spring:
  application:
    name: "configserver"
  profiles:
    active: git
#    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
      rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"


encrypt:
  key: "344G43G4GTROLOLOLO"

server:
  port: 8071
